// Generates src/styles/theme.css (Tailwind v4 @theme + light/dark CSS variables) from src/styles/tokens.json,
// plus backend/public/site/tokens.css + fonts for the Blade landing and share pages (same tokens, no build step).
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(readFileSync(resolve(root, 'src/styles/tokens.json'), 'utf8'))

const theme = []
const light = []
const dark = []

// Remove Tailwind's default palette so components can only use design tokens.
theme.push('  --color-*: initial;', '  --color-transparent: transparent;', '  --color-current: currentColor;')

for (const [name, value] of Object.entries(tokens.colors)) {
  theme.push(`  --color-${name}: var(--dc-${name});`)
  light.push(`  --dc-${name}: ${value.light};`)
  dark.push(`  --dc-${name}: ${value.dark};`)
}

for (const [name, value] of Object.entries(tokens.gradients)) {
  light.push(`  --dc-${name}: ${value.light};`)
  dark.push(`  --dc-${name}: ${value.dark};`)
}

for (const [name, value] of Object.entries(tokens.shadows)) {
  theme.push(`  --shadow-${name}: var(--dc-shadow-${name});`)
  light.push(`  --dc-shadow-${name}: ${value.light};`)
  dark.push(`  --dc-shadow-${name}: ${value.dark};`)
}

const quote = (family) => (/^[a-z-]+$/.test(family) ? family : `"${family}"`)
for (const [name, families] of Object.entries(tokens.fonts)) {
  theme.push(`  --font-${name}: ${families.map(quote).join(', ')};`)
}

for (const [name, style] of Object.entries(tokens.typeScale)) {
  theme.push(`  --text-${name}: ${style.size};`)
  theme.push(`  --text-${name}--line-height: ${style.lineHeight};`)
  theme.push(`  --text-${name}--font-weight: ${style.weight};`)
  if (style.tracking) theme.push(`  --text-${name}--letter-spacing: ${style.tracking};`)
}

for (const [name, value] of Object.entries(tokens.spacing)) theme.push(`  --spacing-${name}: ${value};`)
for (const [name, value] of Object.entries(tokens.radii)) theme.push(`  --radius-${name}: ${value};`)
for (const [name, value] of Object.entries(tokens.layout)) theme.push(`  --container-${name}: ${value};`)

const css = `/* GENERATED by scripts/generate-theme.mjs from tokens.json. Do not edit by hand. */

@theme inline {
${theme.join('\n')}
}

:root {
  color-scheme: light;
${light.join('\n')}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${dark.join('\n')}
}
`

writeFileSync(resolve(root, 'src/styles/theme.css'), css)
console.log(
  `theme.css written (${Object.keys(tokens.colors).length} colors, ${Object.keys(tokens.typeScale).length} text styles)`,
)

// ---- Public Blade site (disruptcyprus.com): plain CSS variables, follows the system theme --------------------------

const siteDir = resolve(root, '../backend/public/site')
if (existsSync(resolve(root, '../backend/public'))) {
  mkdirSync(resolve(siteDir, 'fonts'), { recursive: true })

  const siteVars = []
  for (const [name, families] of Object.entries(tokens.fonts)) {
    siteVars.push(`  --dc-font-${name}: ${families.map(quote).join(', ')};`)
  }
  for (const [name, style] of Object.entries(tokens.typeScale)) {
    siteVars.push(`  --dc-text-${name}: ${style.weight} ${style.size}/${style.lineHeight} var(--dc-font-${name.startsWith('headline') ? 'headline' : name.startsWith('body') ? 'body' : 'ui'});`)
    if (style.tracking) siteVars.push(`  --dc-tracking-${name}: ${style.tracking};`)
  }
  for (const [name, value] of Object.entries(tokens.spacing)) siteVars.push(`  --dc-${name}: ${value};`)
  for (const [name, value] of Object.entries(tokens.radii)) siteVars.push(`  --dc-radius-${name}: ${value};`)
  for (const [name, value] of Object.entries(tokens.layout)) siteVars.push(`  --dc-container-${name}: ${value};`)

  // Only the Latin + Greek subsets the site needs, copied next to the CSS (no third-party font requests).
  const fontFaces = []
  const fontPackages = ['playfair-display', 'noto-serif-display', 'source-serif-4', 'inter']
  for (const pkg of fontPackages) {
    const css = readFileSync(resolve(root, `node_modules/@fontsource-variable/${pkg}/wght.css`), 'utf8')
    for (const block of css.match(/@font-face \{[^}]+\}/g) ?? []) {
      const file = block.match(/files\/([^)]+-(latin|greek)-wght-normal\.woff2)/)?.[1]
      if (!file || (pkg === 'noto-serif-display' && file.includes('latin'))) continue
      copyFileSync(resolve(root, `node_modules/@fontsource-variable/${pkg}/files/${file}`), resolve(siteDir, 'fonts', file))
      fontFaces.push(block.replace(/url\(\.\/files\//, 'url(fonts/'))
    }
  }

  // App icons, shared with the PWA (web/public).
  for (const [from, to] of [
    ['favicon.svg', 'favicon.svg'],
    ['apple-touch-icon-180x180.png', 'apple-touch-icon-180x180.png'],
    ['pwa-512x512.png', 'logo-512.png'],
  ]) {
    copyFileSync(resolve(root, 'public', from), resolve(siteDir, to))
  }

  writeFileSync(
    resolve(siteDir, 'tokens.css'),
    `/* GENERATED by web/scripts/generate-theme.mjs from web/src/styles/tokens.json. Do not edit by hand. */

${fontFaces.join('\n\n')}

:root {
  color-scheme: light dark;
${light.join('\n')}
${siteVars.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root {
${dark.map((line) => `  ${line}`).join('\n')}
  }
}
`,
  )
  console.log(`site tokens.css written (${fontFaces.length} font faces)`)
}
