// Generates src/styles/theme.css (Tailwind v4 @theme + light/dark CSS variables) from src/styles/tokens.json.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const tokens = JSON.parse(readFileSync(resolve(root, 'src/styles/tokens.json'), 'utf8'))

const theme = []
const light = []
const dark = []

// Remove Tailwind's default palette so components can only use design tokens.
theme.push('  --color-*: initial;', '  --color-transparent: transparent;', '  --color-current: currentColor;')

for (const [name, value] of Object.entries(tokens.colors)) {
  theme.push(`  --color-${name}: var(--dc-${name});`)
  light.push(`  --dc-${name}: ${value.light};`)
  dark.push(`  --dc-${name}: ${value.dark};`)
}

for (const [name, value] of Object.entries(tokens.gradients)) {
  light.push(`  --dc-${name}: ${value.light};`)
  dark.push(`  --dc-${name}: ${value.dark};`)
}

for (const [name, value] of Object.entries(tokens.shadows)) {
  theme.push(`  --shadow-${name}: var(--dc-shadow-${name});`)
  light.push(`  --dc-shadow-${name}: ${value.light};`)
  dark.push(`  --dc-shadow-${name}: ${value.dark};`)
}

const quote = (family) => (/^[a-z-]+$/.test(family) ? family : `"${family}"`)
for (const [name, families] of Object.entries(tokens.fonts)) {
  theme.push(`  --font-${name}: ${families.map(quote).join(', ')};`)
}

for (const [name, style] of Object.entries(tokens.typeScale)) {
  theme.push(`  --text-${name}: ${style.size};`)
  theme.push(`  --text-${name}--line-height: ${style.lineHeight};`)
  theme.push(`  --text-${name}--font-weight: ${style.weight};`)
  if (style.tracking) theme.push(`  --text-${name}--letter-spacing: ${style.tracking};`)
}

for (const [name, value] of Object.entries(tokens.spacing)) theme.push(`  --spacing-${name}: ${value};`)
for (const [name, value] of Object.entries(tokens.radii)) theme.push(`  --radius-${name}: ${value};`)
for (const [name, value] of Object.entries(tokens.layout)) theme.push(`  --container-${name}: ${value};`)

const css = `/* GENERATED by scripts/generate-theme.mjs from tokens.json. Do not edit by hand. */

@theme inline {
${theme.join('\n')}
}

:root {
  color-scheme: light;
${light.join('\n')}
}

:root[data-theme='dark'] {
  color-scheme: dark;
${dark.join('\n')}
}
`

writeFileSync(resolve(root, 'src/styles/theme.css'), css)
console.log(
  `theme.css written (${Object.keys(tokens.colors).length} colors, ${Object.keys(tokens.typeScale).length} text styles)`,
)
